services:
  go_app:
    container_name: go_app
    image: go-api-tutorial
    build: .
    ports:
      - '80:80'
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - go_db
    ports:
      - 81:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=mkdigo@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata: {}
  pgadmin: {}
